// apps/react-remote-one/src/App.jsx
import { useState, useEffect } from "react";
import { lang } from "store/xoid";
import styles from "./App.module.css"

const App = ({ title = 'Bootstrapped' }) => {
  const [useLangXoid, setUseLangXoid] = useState(lang.value);
 useEffect(() => {
    //Your code here
    lang?.watch(
    (state) => setUseLangXoid(state)
  )
  }, [useLangXoid])

  const updateLang = (val) => {
    lang?.update(() => val);
  }
  
  return (
    <div className={styles['remote-one']}>
      <h2>🥳 React Remote one {title}</h2>
      <input value={useLangXoid} onChange={e => updateLang(e.target.value)}/>
      xoid: {useLangXoid}
    </div>
  )
};


export default App;

// apps/vue-remote-one/src/App.vue
<script setup>
import { ref, watch } from 'vue'
import { lang } from "store/xoid";

const props = defineProps({
  title: {
    type: String,
    default: 'Bootstraped'
  }
})

const langVal = ref(lang.value)
const title = ref(props.title)

lang.watch(
  (state) => langVal.value = state
)

watch(langVal, (val) => {
  lang.update(() => val)
})

</script>


<template>
  <div class="vue-app">
    <h2>Vue Remote One {{ title }}</h2>
    xoid: <input v-model="langVal" />
    {{ langVal }}
  </div>
</template>

<style lang="scss" scoped>
.vue-app {
  border: 1px solid var(--color-font-base, black);
  border-radius: 12px;
  color: var(--color-font-base, black);
  padding: 12px;
  h2 {
    color: var(--color-font-inverse, black);
    background-color: var(--color-action-primary-base, rgb(91, 188, 91));
  }
}

</style>
