// apps/react-remote-one/src/App.jsx
import { useState, useEffect } from "react";
import { lang } from "store/xoid";
import styles from "./App.module.css"

const App = ({ title = 'Bootstrapped' }) => {
  const [useLangXoid, setUseLangXoid] = useState(lang.value);
 useEffect(() => {
    //Your code here
    lang?.watch(
    (state) => setUseLangXoid(state)
  )
  }, [useLangXoid])

  const updateLang = (val) => {
    lang?.update(() => val);
  }
  
  return (
    <div className={styles['remote-one']}>
      <h2>🥳 React Remote one {title}</h2>
      <input value={useLangXoid} onChange={e => updateLang(e.target.value)}/>
      xoid: {useLangXoid}
    </div>
  )
};


export default App;

// apps/vue-remote-one/src/App.jsx
import { defineComponent, ref, watchEffect } from 'vue';
import { lang } from "store/xoid";
import styles from './App.module.css';
export const App = defineComponent({
  props: {
    title: {
      type: String,
      default: 'Bootstrapped'
    },
  },
  setup(props) {
    console.log(styles)
    const useLangXoid = ref(lang.value);
    lang?.watch(
        (state) => useLangXoid.value = state
      )

    watchEffect(
      () => {
        lang.update(() => useLangXoid.value)
      }
    );

    return () => <div class={styles['remote-one']}>
      <h2>Vue JSX Remote One {props.title}</h2>
      <input v-model={useLangXoid.value}/>
        xoid: {useLangXoid.value}
    </div>
  }
});

export default App;
